"""Initial migration.

Revision ID: 524b262ce399
Revises: 
Create Date: 2024-08-08 23:30:24.066380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524b262ce399'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_file')
    # ### end Alembic commands ###
